# Generated by Django 2.2 on 2022-03-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220302_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatarURL',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
