# Generated by Django 2.2 on 2022-03-06 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tweet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='reply_to',
            new_name='replying_to',
        ),
    ]
